export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIOS= 'OBTENER_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const VERIFICAR_USUARIO = 'VERIFICAR_USUARIO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const CARGAR_USUARIO = 'CARGAR_USUARIO';

export const ACTIVE_TOGGLE = 'ACTIVE_TOGGLE';
export const IR_CURSO = 'IR_CURSO';